-- MySQL Script generated by MySQL Workbench
-- Tue Jul 29 07:14:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema khachsan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema khachsan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `khachsan` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `khachsan` ;

-- -----------------------------------------------------
-- Table `khachsan`.`kieu_phong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`kieu_phong` (
  `ID_KP` VARCHAR(10) NOT NULL,
  `TEN_KP` VARCHAR(100) NOT NULL,
  `MO_TA` VARCHAR(500) NULL DEFAULT NULL,
  `SO_LUONG_KHACH_O` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_KP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`loai_phong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`loai_phong` (
  `ID_LP` VARCHAR(10) NOT NULL,
  `TEN_LP` VARCHAR(100) NOT NULL,
  `MO_TA` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_LP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`hang_phong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`hang_phong` (
  `ID_HANG_PHONG` INT NOT NULL AUTO_INCREMENT,
  `ID_KP` VARCHAR(10) NULL DEFAULT NULL,
  `ID_LP` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_HANG_PHONG`),
  INDEX `ID_KP` (`ID_KP` ASC) VISIBLE,
  INDEX `ID_LP` (`ID_LP` ASC) VISIBLE,
  CONSTRAINT `fk_hp_kp`
    FOREIGN KEY (`ID_KP`)
    REFERENCES `khachsan`.`kieu_phong` (`ID_KP`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_hp_lp`
    FOREIGN KEY (`ID_LP`)
    REFERENCES `khachsan`.`loai_phong` (`ID_LP`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`anh_hang_phong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`anh_hang_phong` (
  `ID_ANH_HANG_PHONG` VARCHAR(255) NOT NULL,
  `URL_ANH` VARCHAR(255) NULL DEFAULT NULL,
  `ID_HANG_PHONG` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ANH_HANG_PHONG`),
  INDEX `ID_HANG_PHONG` (`ID_HANG_PHONG` ASC) VISIBLE,
  CONSTRAINT `fk_anh_hp`
    FOREIGN KEY (`ID_HANG_PHONG`)
    REFERENCES `khachsan`.`hang_phong` (`ID_HANG_PHONG`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`bo_phan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`bo_phan` (
  `ID_BP` VARCHAR(10) NOT NULL,
  `TENBP` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_BP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`trangthai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`trangthai` (
  `ID_TT` VARCHAR(10) NOT NULL,
  `TEN_TRANG_THAI` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_TT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`phong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`phong` (
  `SOPHONG` VARCHAR(10) NOT NULL,
  `TANG` INT NULL DEFAULT NULL,
  `ID_HANG_PHONG` INT NULL DEFAULT NULL,
  `ID_TT` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`SOPHONG`),
  INDEX `ID_HANG_PHONG` (`ID_HANG_PHONG` ASC) VISIBLE,
  INDEX `ID_TT` (`ID_TT` ASC) VISIBLE,
  CONSTRAINT `fk_p_hp`
    FOREIGN KEY (`ID_HANG_PHONG`)
    REFERENCES `khachsan`.`hang_phong` (`ID_HANG_PHONG`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_p_tt`
    FOREIGN KEY (`ID_TT`)
    REFERENCES `khachsan`.`trangthai` (`ID_TT`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`khach_hang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`khach_hang` (
  `CCCD` VARCHAR(20) NOT NULL,
  `HO` VARCHAR(50) NOT NULL,
  `TEN` VARCHAR(50) NOT NULL,
  `SDT` VARCHAR(255) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(100) NULL DEFAULT NULL,
  `DIA_CHI` VARCHAR(200) NULL DEFAULT NULL,
  `MA_SO_THUE` VARCHAR(20) NULL DEFAULT NULL,
  `MAT_KHAU` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`CCCD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`nhan_vien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`nhan_vien` (
  `ID_NV` VARCHAR(10) NOT NULL,
  `HO` VARCHAR(50) NOT NULL,
  `TEN` VARCHAR(50) NOT NULL,
  `PHAI` VARCHAR(255) NULL DEFAULT NULL,
  `NGAY_SINH` DATE NULL DEFAULT NULL,
  `DIA_CHI` VARCHAR(200) NULL DEFAULT NULL,
  `SDT` VARCHAR(255) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(100) NULL DEFAULT NULL,
  `HINH` VARCHAR(200) NULL DEFAULT NULL,
  `USERNAME` VARCHAR(50) NULL DEFAULT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `ID_BP` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_NV`),
  INDEX `ID_BP` (`ID_BP` ASC) VISIBLE,
  CONSTRAINT `fk_nv_bp`
    FOREIGN KEY (`ID_BP`)
    REFERENCES `khachsan`.`bo_phan` (`ID_BP`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`phieudat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`phieudat` (
  `ID_PD` INT NOT NULL AUTO_INCREMENT,
  `NGAY_DAT` DATE NULL DEFAULT NULL,
  `NGAY_BD_THUE` DATE NULL DEFAULT NULL,
  `NGAY_DI` DATE NULL DEFAULT NULL,
  `TRANG_THAI` VARCHAR(255) NULL DEFAULT NULL,
  `SO_TIEN_COC` DECIMAL(38,2) NULL DEFAULT NULL,
  `CCCD` VARCHAR(20) NULL DEFAULT NULL,
  `ID_NV` VARCHAR(10) NULL DEFAULT NULL,
  `CREATED_AT` DATETIME(6) NULL DEFAULT NULL,
  `CREATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `UPDATED_AT` DATETIME(6) NULL DEFAULT NULL,
  `UPDATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PD`),
  INDEX `CCCD` (`CCCD` ASC) VISIBLE,
  INDEX `ID_NV` (`ID_NV` ASC) VISIBLE,
  CONSTRAINT `fk_pd_kh`
    FOREIGN KEY (`CCCD`)
    REFERENCES `khachsan`.`khach_hang` (`CCCD`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pd_nv`
    FOREIGN KEY (`ID_NV`)
    REFERENCES `khachsan`.`nhan_vien` (`ID_NV`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`phieuthue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`phieuthue` (
  `ID_PT` INT NOT NULL AUTO_INCREMENT,
  `NGAY_LAP` DATE NULL DEFAULT NULL,
  `NGAY_DEN` DATE NULL DEFAULT NULL,
  `NGAY_DI` DATE NULL DEFAULT NULL,
  `ID_NV` VARCHAR(10) NULL DEFAULT NULL,
  `CCCD` VARCHAR(20) NULL DEFAULT NULL,
  `ID_PD` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PT`),
  INDEX `ID_NV` (`ID_NV` ASC) VISIBLE,
  INDEX `CCCD` (`CCCD` ASC) VISIBLE,
  INDEX `ID_PD` (`ID_PD` ASC) VISIBLE,
  CONSTRAINT `fk_pt_kh`
    FOREIGN KEY (`CCCD`)
    REFERENCES `khachsan`.`khach_hang` (`CCCD`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pt_nv`
    FOREIGN KEY (`ID_NV`)
    REFERENCES `khachsan`.`nhan_vien` (`ID_NV`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pt_pd`
    FOREIGN KEY (`ID_PD`)
    REFERENCES `khachsan`.`phieudat` (`ID_PD`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`ct_phieu_thue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`ct_phieu_thue` (
  `ID_CT_PT` INT NOT NULL AUTO_INCREMENT,
  `NGAY_DEN` DATE NULL DEFAULT NULL,
  `GIO_DEN` TIME NULL DEFAULT NULL,
  `NGAY_DI` DATE NULL DEFAULT NULL,
  `DON_GIA` DECIMAL(38,2) NULL DEFAULT NULL,
  `TT_THANH_TOAN` VARCHAR(255) NULL DEFAULT NULL,
  `ID_PT` INT NULL DEFAULT NULL,
  `SO_PHONG` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CT_PT`),
  INDEX `ID_PT` (`ID_PT` ASC) VISIBLE,
  INDEX `SO_PHONG` (`SO_PHONG` ASC) VISIBLE,
  CONSTRAINT `fk_ctpt_p`
    FOREIGN KEY (`SO_PHONG`)
    REFERENCES `khachsan`.`phong` (`SOPHONG`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ctpt_pt`
    FOREIGN KEY (`ID_PT`)
    REFERENCES `khachsan`.`phieuthue` (`ID_PT`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`dich_vu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`dich_vu` (
  `ID_DV` VARCHAR(10) NOT NULL,
  `TEN_DV` VARCHAR(255) NULL DEFAULT NULL,
  `DON_VI_TINH` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_DV`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`hoa_don`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`hoa_don` (
  `ID_HD` VARCHAR(10) NOT NULL,
  `NGAY_LAP` DATE NULL DEFAULT NULL,
  `TONG_TIEN` DECIMAL(38,2) NULL DEFAULT NULL,
  `TRANG_THAI` VARCHAR(255) NULL DEFAULT NULL,
  `ID_NV` VARCHAR(10) NULL DEFAULT NULL,
  `ID_CT_PT` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_HD`),
  INDEX `ID_NV` (`ID_NV` ASC) VISIBLE,
  INDEX `ID_CT_PT` (`ID_CT_PT` ASC) VISIBLE,
  CONSTRAINT `fk_hd_ctpt`
    FOREIGN KEY (`ID_CT_PT`)
    REFERENCES `khachsan`.`ct_phieu_thue` (`ID_CT_PT`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_hd_nv`
    FOREIGN KEY (`ID_NV`)
    REFERENCES `khachsan`.`nhan_vien` (`ID_NV`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`ct_dich_vu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`ct_dich_vu` (
  `ID_CT_DV` VARCHAR(255) NOT NULL,
  `ID_CT_PT` INT NULL DEFAULT NULL,
  `ID_DV` VARCHAR(10) NULL DEFAULT NULL,
  `NGAY_SU_DUNG` DATE NULL DEFAULT NULL,
  `GHI_CHU` VARCHAR(255) NULL DEFAULT NULL,
  `GIA` DECIMAL(38,2) NULL DEFAULT NULL,
  `SO_LUONG` INT NULL DEFAULT NULL,
  `TT_THANH_TOAN` VARCHAR(255) NULL DEFAULT NULL,
  `ID_HD` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CT_DV`),
  INDEX `ID_CT_PT` (`ID_CT_PT` ASC) VISIBLE,
  INDEX `ID_DV` (`ID_DV` ASC) VISIBLE,
  INDEX `ID_HD` (`ID_HD` ASC) VISIBLE,
  CONSTRAINT `fk_cdv_ctpt`
    FOREIGN KEY (`ID_CT_PT`)
    REFERENCES `khachsan`.`ct_phieu_thue` (`ID_CT_PT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cdv_dv`
    FOREIGN KEY (`ID_DV`)
    REFERENCES `khachsan`.`dich_vu` (`ID_DV`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cdv_hd`
    FOREIGN KEY (`ID_HD`)
    REFERENCES `khachsan`.`hoa_don` (`ID_HD`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`phu_thu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`phu_thu` (
  `ID_PHU_THU` VARCHAR(10) NOT NULL,
  `TEN_PHU_THU` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PHU_THU`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`ct_phu_thu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`ct_phu_thu` (
  `ID_CT_PHU_THU` VARCHAR(255) NOT NULL,
  `ID_PHU_THU` VARCHAR(10) NULL DEFAULT NULL,
  `ID_CT_PT` INT NULL DEFAULT NULL,
  `TT_THANH_TOAN` VARCHAR(255) NULL DEFAULT NULL,
  `DON_GIA` DECIMAL(38,2) NULL DEFAULT NULL,
  `SO_LUONG` INT NULL DEFAULT NULL,
  `ID_HD` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CT_PHU_THU`),
  INDEX `ID_PHU_THU` (`ID_PHU_THU` ASC) VISIBLE,
  INDEX `ID_CT_PT` (`ID_CT_PT` ASC) VISIBLE,
  INDEX `ID_HD` (`ID_HD` ASC) VISIBLE,
  CONSTRAINT `fk_cpt_hd`
    FOREIGN KEY (`ID_HD`)
    REFERENCES `khachsan`.`hoa_don` (`ID_HD`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cpt_pt`
    FOREIGN KEY (`ID_CT_PT`)
    REFERENCES `khachsan`.`ct_phieu_thue` (`ID_CT_PT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cpt_ptu`
    FOREIGN KEY (`ID_PHU_THU`)
    REFERENCES `khachsan`.`phu_thu` (`ID_PHU_THU`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`ctkhacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`ctkhacho` (
  `ID_CT_PT` INT NOT NULL,
  `CCCD` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_CT_PT`, `CCCD`),
  INDEX `CCCD` (`CCCD` ASC) VISIBLE,
  CONSTRAINT `fk_ckh_ctpt`
    FOREIGN KEY (`ID_CT_PT`)
    REFERENCES `khachsan`.`ct_phieu_thue` (`ID_CT_PT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ckh_kh`
    FOREIGN KEY (`CCCD`)
    REFERENCES `khachsan`.`khach_hang` (`CCCD`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`khuyenmai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`khuyenmai` (
  `ID_KM` VARCHAR(10) NOT NULL,
  `MO_TA_KM` VARCHAR(255) NULL DEFAULT NULL,
  `NGAY_BAT_DAU` DATE NULL DEFAULT NULL,
  `NGAY_KET_THUC` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID_KM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`ctkhuyenmai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`ctkhuyenmai` (
  `ID_KM` VARCHAR(10) NOT NULL,
  `ID_HANGPHONG` INT NOT NULL,
  `PHAN_TRAM_GIAM` DECIMAL(38,2) NULL DEFAULT NULL,
  `ID_HANG_PHONG` INT NOT NULL,
  PRIMARY KEY (`ID_KM`, `ID_HANGPHONG`),
  INDEX `ID_HANGPHONG` (`ID_HANGPHONG` ASC) VISIBLE,
  INDEX `FK92tovkvg7m02tmnbh3btapy32` (`ID_HANG_PHONG` ASC) VISIBLE,
  CONSTRAINT `FK92tovkvg7m02tmnbh3btapy32`
    FOREIGN KEY (`ID_HANG_PHONG`)
    REFERENCES `khachsan`.`hang_phong` (`ID_HANG_PHONG`),
  CONSTRAINT `fk_km_hp`
    FOREIGN KEY (`ID_HANGPHONG`)
    REFERENCES `khachsan`.`hang_phong` (`ID_HANG_PHONG`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_km_km`
    FOREIGN KEY (`ID_KM`)
    REFERENCES `khachsan`.`khuyenmai` (`ID_KM`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`doiphong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`doiphong` (
  `ID_CT_PT` INT NOT NULL,
  `SOPHONGMOI` VARCHAR(10) NOT NULL,
  `NGAY_DEN` DATE NULL DEFAULT NULL,
  `NGAY_DI` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CT_PT`, `SOPHONGMOI`),
  INDEX `SOPHONGMOI` (`SOPHONGMOI` ASC) VISIBLE,
  CONSTRAINT `fk_dp_ctpt`
    FOREIGN KEY (`ID_CT_PT`)
    REFERENCES `khachsan`.`ct_phieu_thue` (`ID_CT_PT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dp_p`
    FOREIGN KEY (`SOPHONGMOI`)
    REFERENCES `khachsan`.`phong` (`SOPHONG`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`gia_dich_vu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`gia_dich_vu` (
  `ID_DV` VARCHAR(10) NOT NULL,
  `NGAY_AP_DUNG` DATE NOT NULL,
  `GIA` DECIMAL(38,2) NULL DEFAULT NULL,
  `ID_NV` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_DV`, `NGAY_AP_DUNG`),
  INDEX `ID_DV` (`ID_DV` ASC) VISIBLE,
  INDEX `ID_NV` (`ID_NV` ASC) VISIBLE,
  CONSTRAINT `fk_gdv_dv`
    FOREIGN KEY (`ID_DV`)
    REFERENCES `khachsan`.`dich_vu` (`ID_DV`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gdv_nv`
    FOREIGN KEY (`ID_NV`)
    REFERENCES `khachsan`.`nhan_vien` (`ID_NV`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`gia_phong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`gia_phong` (
  `ID_GIA_PHONG` INT NOT NULL AUTO_INCREMENT,
  `ID_HANG_PHONG` INT NOT NULL,
  `NGAY_AP_DUNG` DATE NOT NULL,
  `GIA` DECIMAL(15,2) NOT NULL,
  `ID_NV` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_GIA_PHONG`),
  INDEX `ID_HANG_PHONG` (`ID_HANG_PHONG` ASC) VISIBLE,
  INDEX `ID_NV` (`ID_NV` ASC) VISIBLE,
  CONSTRAINT `gia_phong_ibfk_1`
    FOREIGN KEY (`ID_HANG_PHONG`)
    REFERENCES `khachsan`.`hang_phong` (`ID_HANG_PHONG`),
  CONSTRAINT `gia_phong_ibfk_2`
    FOREIGN KEY (`ID_NV`)
    REFERENCES `khachsan`.`nhan_vien` (`ID_NV`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`nhom_quyen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`nhom_quyen` (
  `ID_NQ` VARCHAR(10) NOT NULL,
  `TEN_NQ` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_NQ`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`phan_quyen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`phan_quyen` (
  `ID_NQ` VARCHAR(10) NOT NULL,
  `ID_BP` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_NQ`, `ID_BP`),
  INDEX `ID_BP` (`ID_BP` ASC) VISIBLE,
  CONSTRAINT `fk_pq_bp`
    FOREIGN KEY (`ID_BP`)
    REFERENCES `khachsan`.`bo_phan` (`ID_BP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pq_nq`
    FOREIGN KEY (`ID_NQ`)
    REFERENCES `khachsan`.`nhom_quyen` (`ID_NQ`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`quan_ly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`quan_ly` (
  `ID_BP` VARCHAR(10) NOT NULL,
  `MANV` VARCHAR(10) NOT NULL,
  `NGAYBDQL` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID_BP`, `MANV`),
  INDEX `MANV` (`MANV` ASC) VISIBLE,
  CONSTRAINT `fk_ql_bp`
    FOREIGN KEY (`ID_BP`)
    REFERENCES `khachsan`.`bo_phan` (`ID_BP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ql_nv`
    FOREIGN KEY (`MANV`)
    REFERENCES `khachsan`.`nhan_vien` (`ID_NV`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`thay_doi_gia_phu_thu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`thay_doi_gia_phu_thu` (
  `ID_PHU_THU` VARCHAR(10) NOT NULL,
  `NGAY_AP_DUNG` DATE NOT NULL,
  `GIA` DECIMAL(38,2) NULL DEFAULT NULL,
  `ID_NV` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PHU_THU`, `NGAY_AP_DUNG`),
  INDEX `ID_PHU_THU` (`ID_PHU_THU` ASC) VISIBLE,
  INDEX `ID_NV` (`ID_NV` ASC) VISIBLE,
  CONSTRAINT `fk_tdgt_nv`
    FOREIGN KEY (`ID_NV`)
    REFERENCES `khachsan`.`nhan_vien` (`ID_NV`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tdgt_pt`
    FOREIGN KEY (`ID_PHU_THU`)
    REFERENCES `khachsan`.`phu_thu` (`ID_PHU_THU`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `khachsan`.`tiennghi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `khachsan`.`tiennghi` (
  `ID_TN` VARCHAR(255) NOT NULL,
  `TEN_TN` VARCHAR(255) NULL DEFAULT NULL,
  `ICON` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_TN`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `khachsan` ;

-- -----------------------------------------------------
-- procedure sp_GetAvailableRoomsByCategory
-- -----------------------------------------------------

DELIMITER $$
USE `khachsan`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_GetAvailableRoomsByCategory`()
BEGIN
    SELECT 
        p.SOPHONG AS 'Phòng',
        CONCAT(kp.TEN_KP, ' - ', lp.TEN_LP) AS 'Hạng phòng',
        COALESCE(gp.GIA, 0) AS 'Giá (VNĐ)',
        p.TANG AS 'Tầng',
        kp.SO_LUONG_KHACH_O AS 'Số khách tối đa'
    FROM phong p
    INNER JOIN hang_phong hp ON p.ID_HANG_PHONG = hp.ID_HANG_PHONG
    INNER JOIN kieu_phong kp ON hp.ID_KP = kp.ID_KP
    INNER JOIN loai_phong lp ON hp.ID_LP = lp.ID_LP
    INNER JOIN trangthai tt ON p.ID_TT = tt.ID_TT
    LEFT JOIN (
        SELECT 
            gdv.ID_DV,
            gdv.GIA,
            ROW_NUMBER() OVER (PARTITION BY gdv.ID_DV ORDER BY gdv.NGAY_AP_DUNG DESC) as rn
        FROM gia_dich_vu gdv
        WHERE gdv.NGAY_AP_DUNG <= CURDATE()
    ) gp ON kp.ID_KP = gp.ID_DV AND gp.rn = 1
    WHERE tt.TEN_TRANG_THAI = 'Trống'
    ORDER BY p.TANG, p.SOPHONG;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_GetBookingByCustomerAndDate
-- -----------------------------------------------------

DELIMITER $$
USE `khachsan`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_GetBookingByCustomerAndDate`(
    IN cmnd VARCHAR(20),
    IN ngay_dat DATE
)
BEGIN
    SELECT 
        pd.ID_PD AS 'Số phiếu đặt',
        CONCAT(kp.TEN_KP, ' - ', lp.TEN_LP) AS 'Hạng phòng',
        COUNT(DISTINCT ctpt.SO_PHONG) AS 'Số lượng phòng',
        COALESCE(gp.GIA, 0) AS 'Giá (VNĐ)',
        pd.NGAY_BD_THUE AS 'Ngày bắt đầu thuê',
        DATEDIFF(pd.NGAY_DI, pd.NGAY_BD_THUE) AS 'Số ngày thuê dự kiến',
        pd.SO_TIEN_COC AS 'Tiền cọc (VNĐ)',
        pd.TRANG_THAI AS 'Trạng thái',
        CONCAT(kh.HO, ' ', kh.TEN) AS 'Tên khách hàng',
        kh.SDT AS 'Số điện thoại',
        kh.EMAIL AS 'Email'
    FROM phieudat pd
    INNER JOIN khach_hang kh ON pd.CCCD = kh.CCCD
    LEFT JOIN phieuthue pt ON pd.ID_PD = pt.ID_PD
    LEFT JOIN ct_phieu_thue ctpt ON pt.ID_PT = ctpt.ID_PT
    LEFT JOIN phong p ON ctpt.SO_PHONG = p.SOPHONG
    LEFT JOIN hang_phong hp ON p.ID_HANG_PHONG = hp.ID_HANG_PHONG
    LEFT JOIN kieu_phong kp ON hp.ID_KP = kp.ID_KP
    LEFT JOIN loai_phong lp ON hp.ID_LP = lp.ID_LP
    LEFT JOIN (
        SELECT 
            gdv.ID_DV,
            gdv.GIA,
            ROW_NUMBER() OVER (PARTITION BY gdv.ID_DV ORDER BY gdv.NGAY_AP_DUNG DESC) as rn
        FROM gia_dich_vu gdv
        WHERE gdv.NGAY_AP_DUNG <= CURDATE()
    ) gp ON kp.ID_KP = gp.ID_DV AND gp.rn = 1
    WHERE kh.CCCD = cmnd AND pd.NGAY_DAT = ngay_dat
    GROUP BY pd.ID_PD, kp.TEN_KP, lp.TEN_LP, gp.GIA;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_GetRevenueByMonthAndCategory
-- -----------------------------------------------------

DELIMITER $$
USE `khachsan`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_GetRevenueByMonthAndCategory`(IN nam INT)
BEGIN
    SELECT 
        MONTH(hd.NGAY_LAP) AS 'Tháng',
        CONCAT(kp.TEN_KP, ' - ', lp.TEN_LP) AS 'Hạng phòng',
        SUM(hd.TONG_TIEN) AS 'Tổng doanh thu (VNĐ)',
        COUNT(DISTINCT hd.ID_HD) AS 'Số hóa đơn',
        COUNT(DISTINCT ctpt.ID_CT_PT) AS 'Số lần thuê phòng'
    FROM hoa_don hd
    INNER JOIN ct_phieu_thue ctpt ON hd.ID_CT_PT = ctpt.ID_CT_PT
    INNER JOIN phong p ON ctpt.SO_PHONG = p.SOPHONG
    INNER JOIN hang_phong hp ON p.ID_HANG_PHONG = hp.ID_HANG_PHONG
    INNER JOIN kieu_phong kp ON hp.ID_KP = kp.ID_KP
    INNER JOIN loai_phong lp ON hp.ID_LP = lp.ID_LP
    WHERE YEAR(hd.NGAY_LAP) = nam
    GROUP BY MONTH(hd.NGAY_LAP), kp.TEN_KP, lp.TEN_LP
    ORDER BY MONTH(hd.NGAY_LAP), SUM(hd.TONG_TIEN) DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_GetRevenueByService
-- -----------------------------------------------------

DELIMITER $$
USE `khachsan`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_GetRevenueByService`(IN nam INT, IN thang INT)
BEGIN
    SELECT 
        dv.TEN_DV AS 'Dịch vụ',
        dv.DON_VI_TINH AS 'Đơn vị tính',
        SUM(cdv.SO_LUONG) AS 'Tổng số lượng',
        SUM(cdv.GIA * cdv.SO_LUONG) AS 'Tổng doanh thu (VNĐ)',
        COUNT(DISTINCT cdv.ID_CT_DV) AS 'Số lần sử dụng'
    FROM ct_dich_vu cdv
    INNER JOIN dich_vu dv ON cdv.ID_DV = dv.ID_DV
    INNER JOIN ct_phieu_thue ctpt ON cdv.ID_CT_PT = ctpt.ID_CT_PT
    INNER JOIN phieuthue pt ON ctpt.ID_PT = pt.ID_PT
    WHERE YEAR(pt.NGAY_LAP) = nam 
    AND (thang IS NULL OR MONTH(pt.NGAY_LAP) = thang)
    GROUP BY dv.ID_DV, dv.TEN_DV, dv.DON_VI_TINH
    ORDER BY SUM(cdv.GIA * cdv.SO_LUONG) DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_GetRoomStatusSummary
-- -----------------------------------------------------

DELIMITER $$
USE `khachsan`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_GetRoomStatusSummary`()
BEGIN
    SELECT 
        tt.TEN_TRANG_THAI AS 'Trạng thái',
        COUNT(p.SOPHONG) AS 'Số lượng phòng',
        CONCAT(ROUND(COUNT(p.SOPHONG) * 100.0 / (SELECT COUNT(*) FROM phong), 2), '%') AS 'Tỷ lệ'
    FROM phong p
    INNER JOIN trangthai tt ON p.ID_TT = tt.ID_TT
    GROUP BY tt.ID_TT, tt.TEN_TRANG_THAI
    ORDER BY COUNT(p.SOPHONG) DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_SearchRooms
-- -----------------------------------------------------

DELIMITER $$
USE `khachsan`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_SearchRooms`(
    IN ngay_den DATE,
    IN ngay_di DATE,
    IN so_khach INT,
    IN gia_min DECIMAL(10,2),
    IN gia_max DECIMAL(10,2)
)
BEGIN
    SELECT 
        p.SOPHONG AS 'Phòng',
        p.TANG AS 'Tầng',
        CONCAT(kp.TEN_KP, ' - ', lp.TEN_LP) AS 'Hạng phòng',
        kp.SO_LUONG_KHACH_O AS 'Số khách tối đa',
        COALESCE(gp.GIA, 0) AS 'Giá (VNĐ)',
        tt.TEN_TRANG_THAI AS 'Trạng thái',
        DATEDIFF(ngay_di, ngay_den) AS 'Số ngày thuê',
        COALESCE(gp.GIA, 0) * DATEDIFF(ngay_di, ngay_den) AS 'Tổng tiền dự kiến (VNĐ)'
    FROM phong p
    INNER JOIN hang_phong hp ON p.ID_HANG_PHONG = hp.ID_HANG_PHONG
    INNER JOIN kieu_phong kp ON hp.ID_KP = kp.ID_KP
    INNER JOIN loai_phong lp ON hp.ID_LP = lp.ID_LP
    INNER JOIN trangthai tt ON p.ID_TT = tt.ID_TT
    LEFT JOIN (
        SELECT 
            gdv.ID_DV,
            gdv.GIA,
            ROW_NUMBER() OVER (PARTITION BY gdv.ID_DV ORDER BY gdv.NGAY_AP_DUNG DESC) as rn
        FROM gia_dich_vu gdv
        WHERE gdv.NGAY_AP_DUNG <= ngay_den
    ) gp ON kp.ID_KP = gp.ID_DV AND gp.rn = 1
    WHERE tt.TEN_TRANG_THAI = 'Trống'
    AND kp.SO_LUONG_KHACH_O >= so_khach
    AND (gia_min IS NULL OR COALESCE(gp.GIA, 0) >= gia_min)
    AND (gia_max IS NULL OR COALESCE(gp.GIA, 0) <= gia_max)
    AND NOT EXISTS (
        SELECT 1 FROM ct_phieu_thue ctpt2
        WHERE ctpt2.SO_PHONG = p.SOPHONG
        AND (
            (ctpt2.NGAY_DEN <= ngay_den AND ctpt2.NGAY_DI > ngay_den)
            OR (ctpt2.NGAY_DEN < ngay_di AND ctpt2.NGAY_DI >= ngay_di)
            OR (ctpt2.NGAY_DEN >= ngay_den AND ctpt2.NGAY_DI <= ngay_di)
        )
    )
    ORDER BY COALESCE(gp.GIA, 0);
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
