
CREATE SCHEMA `khachsan` DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
USE `khachsan`;

-- Disable FKs while building
SET FOREIGN_KEY_CHECKS=0;

-- 1. Loại phòng
CREATE TABLE `loai_phong` (
  `ID_LP`        VARCHAR(10) NOT NULL,
  `TEN_LP`       VARCHAR(10) NULL,
  `MO_TA`        VARCHAR(100) NULL,
  PRIMARY KEY (`ID_LP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Kiểu phòng
CREATE TABLE `kieu_phong` (
  `ID_KP`        VARCHAR(10) NOT NULL,
  `TEN_KP`       VARCHAR(10) NULL,
  `MO_TA`        VARCHAR(100) NULL,
  `SO_LUONG_KHACH_O` INT NULL,
  PRIMARY KEY (`ID_KP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Hạng phòng
CREATE TABLE `hang_phong` (
  `ID_HANG_PHONG` INT         NOT NULL AUTO_INCREMENT,
  `ID_KP`         VARCHAR(10) NULL,
  `ID_LP`         VARCHAR(10) NULL,
  PRIMARY KEY (`ID_HANG_PHONG`),
  INDEX (`ID_KP`),
  INDEX (`ID_LP`),
  CONSTRAINT `fk_hp_kp`
    FOREIGN KEY (`ID_KP`) REFERENCES `kieu_phong` (`ID_KP`)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_hp_lp`
    FOREIGN KEY (`ID_LP`) REFERENCES `loai_phong` (`ID_LP`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Trạng thái phòng
CREATE TABLE `trangthai` (
  `ID_TT`         VARCHAR(10) NOT NULL,
  `TEN_TRANG_THAI` VARCHAR(10) NULL,
  PRIMARY KEY (`ID_TT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. Phòng
CREATE TABLE `phong` (
  `SOPHONG`       VARCHAR(10) NOT NULL,
  `TANG`          INT NULL,
  `ID_HANG_PHONG` INT NULL,
  `ID_TT`         VARCHAR(10) NULL,
  PRIMARY KEY (`SOPHONG`),
  INDEX (`ID_HANG_PHONG`),
  INDEX (`ID_TT`),
  CONSTRAINT `fk_p_hp`
    FOREIGN KEY (`ID_HANG_PHONG`) REFERENCES `hang_phong` (`ID_HANG_PHONG`)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_p_tt`
    FOREIGN KEY (`ID_TT`) REFERENCES `trangthai` (`ID_TT`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. Tiện nghi
CREATE TABLE `tiennghi` (
  `ID_TN`        VARCHAR(10) NOT NULL,
  `TEN_TN`       VARCHAR(10) NULL,
  `ICON`         VARCHAR(100) NULL,
  PRIMARY KEY (`ID_TN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. Ảnh hạng phòng
CREATE TABLE `anh_hang_phong` (
  `ID_ANH_HANG_PHONG` VARCHAR(10) NOT NULL,
  `URL_ANH`           VARCHAR(100) NULL,
  `ID_HANG_PHONG`     INT NULL,
  PRIMARY KEY (`ID_ANH_HANG_PHONG`),
  INDEX (`ID_HANG_PHONG`),
  CONSTRAINT `fk_anh_hp`
    FOREIGN KEY (`ID_HANG_PHONG`) REFERENCES `hang_phong` (`ID_HANG_PHONG`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. Bộ phận & Nhân viên
CREATE TABLE `bo_phan` (
  `ID_BP`        VARCHAR(10) NOT NULL,
  `TENBP`        VARCHAR(10) NULL,
  PRIMARY KEY (`ID_BP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `nhan_vien` (
  `ID_NV`        VARCHAR(10) NOT NULL,
  `HO`           VARCHAR(10) NULL,
  `TEN`          VARCHAR(10) NULL,
  `PHAI`         VARCHAR(10) NULL,
  `NGAY_SINH`    DATE NULL,
  `DIA_CHI`      VARCHAR(100) NULL,
  `SDT`          VARCHAR(15) NULL,
  `EMAIL`        VARCHAR(50) NULL,
  `HINH`         VARCHAR(100) NULL,
  `USERNAME`     VARCHAR(50) NULL,
  `PASSWORD`     VARCHAR(50) NULL,
  `ID_BP`        VARCHAR(10) NULL,
  PRIMARY KEY (`ID_NV`),
  INDEX (`ID_BP`),
  CONSTRAINT `fk_nv_bp`
    FOREIGN KEY (`ID_BP`) REFERENCES `bo_phan` (`ID_BP`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. Khách hàng
CREATE TABLE `khach_hang` (
  `CCCD`         VARCHAR(20) NOT NULL,
  `HO`           VARCHAR(10) NULL,
  `TEN`          VARCHAR(10) NULL,
  `SDT`          VARCHAR(15) NULL,
  `EMAIL`        VARCHAR(50) NULL,
  `DIA_CHI`      VARCHAR(100) NULL,
  `MA_SO_THUE`   VARCHAR(20) NULL,
  PRIMARY KEY (`CCCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. Phiếu đặt
CREATE TABLE `phieudat` (
  `ID_PD`        INT            NOT NULL AUTO_INCREMENT,
  `NGAY_DAT`     DATE NULL,
  `NGAY_BD_THUE` DATE NULL,
  `NGAY_DI`      DATE NULL,
  `TRANG_THAI`   VARCHAR(20) NULL,
  `SO_TIEN_COC`  DECIMAL(10,2) NULL,
  `CCCD`         VARCHAR(20) NULL,
  `ID_NV`        VARCHAR(10) NULL,
  PRIMARY KEY (`ID_PD`),
  INDEX (`CCCD`),
  INDEX (`ID_NV`),
  CONSTRAINT `fk_pd_kh`
    FOREIGN KEY (`CCCD`) REFERENCES `khach_hang` (`CCCD`)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_pd_nv`
    FOREIGN KEY (`ID_NV`) REFERENCES `nhan_vien` (`ID_NV`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 11. Phiếu thuê
CREATE TABLE `phieuthue` (
  `ID_PT`        INT            NOT NULL AUTO_INCREMENT,
  `NGAY_LAP`     DATE NULL,
  `NGAY_DEN`     DATE NULL,
  `NGAY_DI`      DATE NULL,
  `ID_NV`        VARCHAR(10) NULL,
  `CCCD`         VARCHAR(20) NULL,
  `ID_PD`        INT NULL,
  PRIMARY KEY (`ID_PT`),
  INDEX (`ID_NV`),
  INDEX (`CCCD`),
  INDEX (`ID_PD`),
  CONSTRAINT `fk_pt_nv`
    FOREIGN KEY (`ID_NV`) REFERENCES `nhan_vien` (`ID_NV`)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_pt_kh`
    FOREIGN KEY (`CCCD`) REFERENCES `khach_hang` (`CCCD`)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_pt_pd`
    FOREIGN KEY (`ID_PD`) REFERENCES `phieudat` (`ID_PD`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 12. Chi tiết phiếu thuê
CREATE TABLE `ct_phieu_thue` (
  `ID_CT_PT`     INT            NOT NULL AUTO_INCREMENT,
  `NGAY_DEN`     DATE NULL,
  `GIO_DEN`      TIME NULL,
  `NGAY_DI`      DATE NULL,
  `DON_GIA`      DECIMAL(10,2) NULL,
  `TT_THANH_TOAN` VARCHAR(20)  NULL,
  `ID_PT`        INT           NULL,
  `SO_PHONG`     VARCHAR(10)   NULL,
  PRIMARY KEY (`ID_CT_PT`),
  INDEX (`ID_PT`),
  INDEX (`SO_PHONG`),
  CONSTRAINT `fk_ctpt_pt`
    FOREIGN KEY (`ID_PT`) REFERENCES `phieuthue` (`ID_PT`)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_ctpt_p`
    FOREIGN KEY (`SO_PHONG`) REFERENCES `phong` (`SOPHONG`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 13. Chi tiết khách có trong phiếu thuê
CREATE TABLE `ctkhacho` (
  `ID_CT_PT`     INT          NOT NULL,
  `CCCD`         VARCHAR(20)  NOT NULL,
  PRIMARY KEY (`ID_CT_PT`,`CCCD`),
  INDEX (`CCCD`),
  CONSTRAINT `fk_ckh_ctpt`
    FOREIGN KEY (`ID_CT_PT`) REFERENCES `ct_phieu_thue` (`ID_CT_PT`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_ckh_kh`
    FOREIGN KEY (`CCCD`) REFERENCES `khach_hang` (`CCCD`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 14. Dịch vụ & Giá dịch vụ
CREATE TABLE `dich_vu` (
  `ID_DV`        VARCHAR(10) NOT NULL,
  `TEN_DV`       VARCHAR(10) NULL,
  `DON_VI_TINH`  VARCHAR(20) NULL,
  PRIMARY KEY (`ID_DV`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `gia_dich_vu` (
  `ID_DV`        VARCHAR(10) NOT NULL,
  `NGAY_AP_DUNG` DATE         NOT NULL,
  `GIA`          DECIMAL(10,2) NULL,
  `ID_NV`        VARCHAR(10) NULL,
  PRIMARY KEY (`ID_DV`,`NGAY_AP_DUNG`),
  INDEX (`ID_DV`),
  INDEX (`ID_NV`),
  CONSTRAINT `fk_gdv_dv`
    FOREIGN KEY (`ID_DV`) REFERENCES `dich_vu` (`ID_DV`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_gdv_nv`
    FOREIGN KEY (`ID_NV`) REFERENCES `nhan_vien` (`ID_NV`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 15. Phụ thu & thay đổi giá phụ thu
CREATE TABLE `phu_thu` (
  `ID_PHU_THU`   VARCHAR(10) NOT NULL,
  `TEN_PHU_THU`  VARCHAR(10) NULL,
  PRIMARY KEY (`ID_PHU_THU`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `thay_doi_gia_phu_thu` (
  `ID_PHU_THU`   VARCHAR(10) NOT NULL,
  `NGAY_AP_DUNG` DATE         NOT NULL,
  `GIA`          DECIMAL(10,2) NULL,
  `ID_NV`        VARCHAR(10)  NULL,
  PRIMARY KEY (`ID_PHU_THU`,`NGAY_AP_DUNG`),
  INDEX (`ID_PHU_THU`),
  INDEX (`ID_NV`),
  CONSTRAINT `fk_tdgt_pt`
    FOREIGN KEY (`ID_PHU_THU`) REFERENCES `phu_thu` (`ID_PHU_THU`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_tdgt_nv`
    FOREIGN KEY (`ID_NV`) REFERENCES `nhan_vien` (`ID_NV`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 16. Chi tiết dịch vụ
CREATE TABLE `ct_dich_vu` (
  `ID_CT_DV`     VARCHAR(10) NOT NULL,
  `ID_CT_PT`     INT         NULL,
  `ID_DV`        VARCHAR(10) NULL,
  `NGAY_SU_DUNG` DATE        NULL,
  `GHI_CHU`      VARCHAR(100) NULL,
  `GIA`          DECIMAL(10,2) NULL,
  `SO_LUONG`     INT         NULL,
  `TT_THANH_TOAN` VARCHAR(20) NULL,
  `ID_HD`        VARCHAR(10) NULL,
  PRIMARY KEY (`ID_CT_DV`),
  INDEX (`ID_CT_PT`),
  INDEX (`ID_DV`),
  INDEX (`ID_HD`),
  CONSTRAINT `fk_cdv_ctpt`
    FOREIGN KEY (`ID_CT_PT`) REFERENCES `ct_phieu_thue` (`ID_CT_PT`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_cdv_dv`
    FOREIGN KEY (`ID_DV`) REFERENCES `dich_vu` (`ID_DV`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_cdv_hd`
    FOREIGN KEY (`ID_HD`) REFERENCES `hoa_don` (`ID_HD`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 17. Chi tiết phụ thu
CREATE TABLE `ct_phu_thu` (
  `ID_CT_PHU_THU` VARCHAR(10) NOT NULL,
  `ID_PHU_THU`   VARCHAR(10) NULL,
  `ID_CT_PT`     INT         NULL,
  `TT_THANH_TOAN` VARCHAR(20) NULL,
  `DON_GIA`      DECIMAL(10,2) NULL,
  `SO_LUONG`     INT         NULL,
  `ID_HD`        VARCHAR(10) NULL,
  PRIMARY KEY (`ID_CT_PHU_THU`),
  INDEX (`ID_PHU_THU`),
  INDEX (`ID_CT_PT`),
  INDEX (`ID_HD`),
  CONSTRAINT `fk_cpt_pt`
    FOREIGN KEY (`ID_CT_PT`) REFERENCES `ct_phieu_thue` (`ID_CT_PT`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_cpt_ptu`
    FOREIGN KEY (`ID_PHU_THU`) REFERENCES `phu_thu` (`ID_PHU_THU`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_cpt_hd`
    FOREIGN KEY (`ID_HD`) REFERENCES `hoa_don` (`ID_HD`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 18. Hóa đơn
CREATE TABLE `hoa_don` (
  `ID_HD`        VARCHAR(10) NOT NULL,
  `NGAY_LAP`     DATE        NULL,
  `TONG_TIEN`    DECIMAL(12,2) NULL,
  `TRANG_THAI`   VARCHAR(20) NULL,
  `ID_NV`        VARCHAR(10) NULL,
  `ID_CT_PT`     INT         NULL,
  PRIMARY KEY (`ID_HD`),
  INDEX (`ID_NV`),
  INDEX (`ID_CT_PT`),
  CONSTRAINT `fk_hd_nv`
    FOREIGN KEY (`ID_NV`) REFERENCES `nhan_vien` (`ID_NV`)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_hd_ctpt`
    FOREIGN KEY (`ID_CT_PT`) REFERENCES `ct_phieu_thue` (`ID_CT_PT`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 19. Khuyến mại
CREATE TABLE `khuyenmai` (
  `ID_KM`         VARCHAR(10) NOT NULL,
  `MO_TA_KM`      VARCHAR(100) NULL,
  `NGAY_BAT_DAU`  DATE        NULL,
  `NGAY_KET_THUC` DATE        NULL,
  PRIMARY KEY (`ID_KM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ctkhuyenmai` (
  `ID_KM`        VARCHAR(10) NOT NULL,
  `ID_HANGPHONG` INT         NOT NULL,
  `PHAN_TRAM_GIAM` DECIMAL(5,2) NULL,
  PRIMARY KEY (`ID_KM`,`ID_HANGPHONG`),
  INDEX (`ID_HANGPHONG`),
  CONSTRAINT `fk_km_km`
    FOREIGN KEY (`ID_KM`) REFERENCES `khuyenmai` (`ID_KM`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_km_hp`
    FOREIGN KEY (`ID_HANGPHONG`) REFERENCES `hang_phong` (`ID_HANG_PHONG`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 20. Đổi phòng
CREATE TABLE `doiphong` (
  `ID_CT_PT`     INT         NOT NULL,
  `SOPHONGMOI`   VARCHAR(10) NOT NULL,
  `NGAY_DEN`     DATE        NULL,
  `NGAY_DI`      DATE        NULL,
  PRIMARY KEY (`ID_CT_PT`,`SOPHONGMOI`),
  INDEX (`SOPHONGMOI`),
  CONSTRAINT `fk_dp_ctpt`
    FOREIGN KEY (`ID_CT_PT`) REFERENCES `ct_phieu_thue` (`ID_CT_PT`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_dp_p`
    FOREIGN KEY (`SOPHONGMOI`) REFERENCES `phong` (`SOPHONG`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 21. Nhóm quyền, phân quyền, quản lý
CREATE TABLE `nhom_quyen` (
  `ID_NQ`        VARCHAR(10) NOT NULL,
  `TEN_NQ`       VARCHAR(50) NULL,
  PRIMARY KEY (`ID_NQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `phan_quyen` (
  `ID_NQ`        VARCHAR(10) NOT NULL,
  `ID_BP`        VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_NQ`,`ID_BP`),
  INDEX (`ID_BP`),
  CONSTRAINT `fk_pq_nq`
    FOREIGN KEY (`ID_NQ`) REFERENCES `nhom_quyen` (`ID_NQ`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_pq_bp`
    FOREIGN KEY (`ID_BP`) REFERENCES `bo_phan` (`ID_BP`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `quan_ly` (
  `ID_BP`        VARCHAR(10) NOT NULL,
  `MANV`         VARCHAR(10) NOT NULL,
  `NGAYBDQL`     DATE        NULL,
  PRIMARY KEY (`ID_BP`,`MANV`),
  INDEX (`MANV`),
  CONSTRAINT `fk_ql_bp`
    FOREIGN KEY (`ID_BP`) REFERENCES `bo_phan` (`ID_BP`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_ql_nv`
    FOREIGN KEY (`MANV`) REFERENCES `nhan_vien` (`ID_NV`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Re-enable FKs
SET FOREIGN_KEY_CHECKS=1;
